### ISSUE TITLE
Using beforeEach results in a fatal error

### ISSUE THREAD

**Issue by ezzatron** [danielstjules/pho#24]
Just noticed this when updating [Phony for Pho](https://github.com/eloquent/phony-pho). If you use `beforeEach()`, and it *doesn't* fail, you'll get something like this:

```
Fatal error: Uncaught TypeError: Argument 1 passed to pho\Runnable\Spec::setException() must be an instance of Exception, null given, called in /path/to/vendor/danielstjules/pho/src/Runner/Runner.php on line 318 and defined in /path/to/vendor/danielstjules/pho/src/Runnable/Spec.php:122
Stack trace:
#0 /path/to/vendor/danielstjules/pho/src/Runner/Runner.php(318): pho\Runnable\Spec->setException(NULL)
#1 /path/to/vendor/danielstjules/pho/src/Runner/Runner.php(293): pho\Runner\Runner->runBeforeEachHooks(Object(pho\Suite\Suite), Object(pho\Runnable\Spec))
#2 /path/to/vendor/danielstjules/pho/src/Runner/Runner.php(262): pho\Runner\Runner->runSpecs(Object(pho\Suite\Suite))
#3 /path/to/vendor/danielstjules/pho/src/Runner/Runner.php(193): pho\Runner\Runner->runSuite(Object(pho\Suite\Suite))
#4 /path/to/vendor/danielstjules/ in /path/to/vendor/danielstjules/pho/src/Runnable/Spec.php on line 122
```

I think this is simply because [Pho isn't checking whether `beforeEach` actually produced an exception](https://github.com/danielstjules/pho/blob/08ed0a6/src/Runner/Runner.php#L318):

```php
        if (!$spec->getException() && $hook) {
            $spec->setException($hook->getException());
        }
```

Looks like the same problem exists in a bunch of places in `Runner.php`. Perhaps it went unnoticed because of loose error reporting?

**Comment by danielstjules** [comment]
Thanks for the issue! What version of PHP are you using? And was this using the latest release of pho?

```
$ php --version
PHP 5.6.30 (cli) (built: Feb  7 2017 16:06:52)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

danielstjules:~/git/pho (master=)
$ cat test.php
<?php

error_reporting(E_ALL);

beforeEach(function() {

});

it('test', function() {

});

danielstjules:~/git/pho (master=)
$ pho test.php



Finished in 0.00067 seconds

0 specs, 0 failures
```

**Comment by danielstjules** [comment]
Ignore my last comment, I see it now :) Thanks for letting me know, will write a fix

**Comment by danielstjules** [comment]
Thanks again! You can tell no one uses this haha 😅

**Comment by danielstjules** [comment]
Tagged a new release with the fix https://github.com/danielstjules/pho/releases/tag/1.2.1

**Comment by ezzatron** [comment]
Thanks for the quick fix, seems to be working fine for my use case now.
