### ISSUE TITLE
Catching exceptions out of scope

### ISSUE THREAD

**Issue by vbargl** [danielstjules/pho#25]
I just notice that `pho` do not catch exceptions, when function that is out of scope fails.

```php
describe("simple suite", function() {
    context("with reference", function () {
        $ref = new stdClass();
        $ref->callback = function () {
            throw new Exception();
        };

        it("should just fail", function () use($ref) {
            $ref->callback();
        });
    });
});
```
Result looks something like this:
```text
simple suite
    with reference
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::callback() in ...\test\concurrency\RendezvousChannelSpec.php:14
Stack trace:
#0 ...\vendor\danielstjules\pho\src\Runnable\Runnable.php(31): Closure->{closure}()
#1 ...\vendor\danielstjules\pho\src\Runnable\Runnable.php(31): Closure->__invoke()
#2 ...\vendor\danielstjules\pho\src\Runnable\Spec.php(56): pho\Runnable\Runnable->run()
#3 ...\vendor\danielstjules\pho\src\Runner\Runner.php(351): pho\Runnable\Spec->run()
#4 ...\vendor\danielstjules\pho\src\Runner\Runner.php(294): pho\Runner\Runner->runRunnable(Object(pho\Runnable\Spec))
#5 ...\vendor\danielstjules\pho\src\Runner\Runner.php(262): pho\Runner\Runner->runSpecs(Object(pho\Suite\Suite))
#6 ...\vendor\danielstjules\pho\src\Runner\Runner.php in ...test\concurrency\RendezvousChannelSpec.php on line 14
```

I did not do any deep analysis, but If it helps I can provide more data.

**Comment by vbargl** [comment]
~Okay, my bad. Example code fails by completely my fault. (And, yes I can't read. 🤦‍♂️) But it's bad example. I'll provide another one in a minute and then edit my post.~

**Comment by vbargl** [comment]
Sorry again. The code I tested failed in context and I didn't notice. 
Is there another way I could get informed about fail during context function?
